# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7074d8989b963fe7e2b387fb247732a0e269195357c479857ef69499120610fcd185cc4b760177079e9ff323504b0f19933d69371277b93b51b1c5724ccb8f3

test:
  secret_key_base: 99d4ef67ed8d5fa27158b206219a9da58c42d2dfc7635e728652cd7f0ea19cc4f3049fce41b2b7d92419807acd95b174172300789e4b21190032fd859c03eaee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
