# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e089487569dfee62bbdc6765bb244c41e01bd50b2377d6399c5c91b02b35684f81f50b9057a7adf67888c51ec6241381f03e00d974d370c657ddbe65e97dd142

test:
  secret_key_base: 9786ff3e5e709aa7fd64cf387b24621690aa5335a7da5fa4c9dd5ac74ea00885fcb67a9e57f0e267b2cbd6f8b8a7d73cfbff51611e5ae628ca45a6b89a9911ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
