# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b22ae4f4a4415f2d46f8fdcdee6ea7afd1fc7ed3ac090b4e21ce8dea965848384f07c32d4d4d03c67208b409635eee79a927c2fea7e8d3f781f643ad035b4fc

test:
  secret_key_base: 4ada48f9420ffc50f63942c764978649c401afa7838de8056efff5442b913c94707d0eb616ecb1f78b5d8c0300b648e954f1975b6c500d3a77f9c38b5c060c23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
